"""com ex user id

Revision ID: 0886b0f1e9a5
Revises: 5bba9b67bc03
Create Date: 2024-09-08 18:48:24.144919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0886b0f1e9a5'
down_revision = '5bba9b67bc03'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
