"""foreign_keys2

Revision ID: 5bba9b67bc03
Revises: f7f25d91d214
Create Date: 2024-09-08 18:32:33.691441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bba9b67bc03'
down_revision = 'f7f25d91d214'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'exercises', 'lessons', ['lesson_id'], ['lesson_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exercises', type_='foreignkey')
    # ### end Alembic commands ###
