"""foreign_keys

Revision ID: f7f25d91d214
Revises: cb42d4781f63
Create Date: 2024-09-08 18:09:56.811703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7f25d91d214'
down_revision = 'cb42d4781f63'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('types_of_exercises',
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('type_title', sa.VARCHAR(), nullable=True),
    sa.Column('type_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('type_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('types_of_exercises')
    # ### end Alembic commands ###
