"""add user uuid

Revision ID: f868feab8d71
Revises: caf4f80f5636
Create Date: 2024-09-08 19:33:55.854564

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f868feab8d71'
down_revision = 'caf4f80f5636'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('completed_exercises', sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'completed_exercises', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'completed_exercises', type_='foreignkey')
    op.drop_column('completed_exercises', 'user_id')
    # ### end Alembic commands ###
